package rabbit

import (
	_ "log"

	mq "github.com/rabbitmq/amqp091-go"
)

// TODO: complete the ags for the methods
type MessageQueue interface {
	Publish(queueName string, message string)
	Consume()
}

type RabbitMQClient struct {
	conn    *mq.Connection
	channel *mq.Channel
}

func NewRabbitMQClient(url string) (*RabbitMQClient, error) {
	conn, err := mq.Dial(url)
	if err != nil {
		return nil, err
	}

	channel, err := conn.Channel()
	if err != nil {
		return nil, err
	}

	return &RabbitMQClient{
		conn:    conn,
		channel: channel,
	}, nil
}

func (r *RabbitMQClient) Publish(exchangeName string, message string) error {
	err := r.channel.ExchangeDeclare(
		exchangeName,
		"fanout",
		true,
		false,
		false,
		false,
		nil,
	)
	if err != nil {
		return err
	}

	err = r.channel.Publish(
		exchangeName,
		"",
		false,
		false,
		mq.Publishing{
			ContentType: "text/plain",
			Body:        []byte(message),
		},
	)
	return err
}

func (r *RabbitMQClient) Consume(exchangeName string) (<-chan mq.Delivery, error) {
	err := r.channel.ExchangeDeclare(
		exchangeName,
		"fanout",
		true,
		false,
		false,
		false,
		nil,
	)
	if err != nil {
		return nil, err
	}

	// Create an anonymous, temporary queue
	queue, err := r.channel.QueueDeclare(
		"",    // Name (empty means RabbitMQ generates a unique name)
		false, // Durable
		true,  // Auto-delete
		true,  // Exclusive (only this connection will use it)
		false, // No-wait
		nil,   // Arguments
	)
	if err != nil {
		return nil, err
	}

	// Bind the queue to the fanout exchange
	err = r.channel.QueueBind(
		queue.Name,   // Queue name
		"",           // Routing key (not used for fanout)
		exchangeName, // Exchange name
		false,        // No-wait
		nil,          // Arguments
	)
	if err != nil {
		return nil, err
	}

	// Start consuming from the queue
	msgs, err := r.channel.Consume(
		queue.Name, // Queue name
		"",         // Consumer tag (empty means autogenerated)
		true,       // Auto-acknowledge
		false,      // Exclusive
		false,      // No-local
		false,      // No-wait
		nil,        // Arguments
	)
	return msgs, err
}

// Close gracefully shuts down the RabbitMQ connection and channel.
func (r *RabbitMQClient) Close() {
	// Close the channel and connection
	r.channel.Close()
	r.conn.Close()
}
